[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | build
  | dist
)/
'''
verbose = false
diff = false


[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [".gitignore", ".dockerignore"]
skip_glob = ["*/migrations/*", "*/venv/*"]
known_third_party = ["requests", "numpy", "pandas"]

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
ignore_missing_imports = true
strict_optional = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
exclude = [
    '^file1\.py$',  # Exclude file1.py
    '^dir1/'        # Exclude everything in dir1/
]

[[tool.mypy.overrides]]
module = ["mycode.foo.*"]
disallow_untyped_defs = false

[tool.mypy-numpy]
ignore_missing_imports = true


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
    "integration",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]
pythonpath = [
  "."
]

[tool.pytest.custom_options]
long_running_tests = false